### PR TITLE
Api sccuess .Please check.

### PR DESCRIPTION
**Pull request by TZUHAN07**
Discord account: tzuhan#4998
Api finish.Please check.

http://18.182.137.39:3000/api/attractions?page=4
http://18.182.137.39:3000/api/attractions?page=1&keyword=藝文館所
http://18.182.137.39:3000/api/attractions?page=1&keyword=北
http://18.182.137.39:3000/api/attraction/46
http://18.182.137.39:3000/api/categories

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
1. `images` field of attraction should be a string array where every image URL of attraction should be a element in this array. For example: `["Image URL 1", "Image URL 2", ...]`
2. Use `LIMIT` in SQL to do pagination than get ALL DATA and do it in your own code.

Solve these issues and re-request review.

**Review by cwpeng — CHANGES_REQUESTED** [review]
Almost done. But you still use something like `"select * from attractions order by id "` to calculate max page. Try another way, for example you can use count() in SQL query.

**Review by cwpeng — CHANGES_REQUESTED** [review]
The same technique should be applied in anywhere applicable.

**Comment by TZUHAN07** [comment]
> The same technique should be applied in anywhere applicable.

I see. I will pay attention  to same applications next time

**Review by cwpeng — APPROVED** [review]
OK. Done. Keep Going. :)

**Pull request merged**
