### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by TZUHAN07**
My discord :tzuhan#4998
http://18.182.137.39:3000/

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
Category block contains no category names.

**Comment by TZUHAN07** [comment]
I have corrected category api. It can see now.

**Review by cwpeng — CHANGES_REQUESTED** [review]
Navigator bar should extend to full width.

**Comment by TZUHAN07** [comment]
Correct.

**Comment by cwpeng** [comment]
Re-request review so that I can review for you.

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Pull request merged**
